---
title: "Case Study: Analiza danych o samochodach"
author: "Imię Nazwisko studenta"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Zadania do wykonania

### 1. Wczytanie i podstawowa eksploracja danych

```{r load_data}
library(dplyr)
library(tidyr)


# Wczytaj dane mtcars (są już dostępne w bazowym R)
data(mtcars)
mtcars 

# Wyświetl pierwsze 6 wierszy
count(mt_cars, 6)

# Sprawdź strukturę danych
structure(mtcars)

# Ile jest wierszy w zbiorze danych?
mtcars %>% 
  group_by(mpg) %>% 
  count(mpg)


# Podsumowanie statystyczne

summary(mtcars) 
  

```


### 2. Analiza z pakietem dplyr

```{r dplyr_analysis}
library(dplyr)

# Policz ile samochodów ma daną liczbę cylindrów
mtcars %>% 
  group_by(cyl)

# Stwórz podzbiór danych - tylko samochody z silnikiem V8 (8 cylindrów)

mtcars %>% 
  filter(cyl == 8)


# Ile jest samochodów z silnikiem V8?
mtcars %>% 
  filter(cyl == 8) %>% 
  count(cyl == 8)

# Filtrowanie  aut hp> 200 i sortowanie malejąco wg mpg

mtcars %>% 
  filter(hp > 200) %>% 
  arrange(desc(mpg))


# Jaka jest średnia moc samochodu dla każdej liczby cylindrów?

mtcars %>% 
  group_by(cyl) %>% 
  summarise(srednia_moc == mean(hp))
  


# Które samochody mają najlepsze i najgorsze zużycie paliwa?

```

### 3. Wizualizacja danych

```{r visualization}
library(ggplot2)

# Wykres zużycia paliwa w zależności od liczby cylindrów (boxplot)

ggplot(mtcars, aes(x = cyl, y = mpg, fill = cyl)) +  
  geom_boxplot() 


# Scatter plot: moc vs zużycie paliwa

```




